### PR TITLE
Add autocopy option

### LINKED ISSUE #4: Auto copy to clipboard

### PR DESCRIPTION
**Pull request by tmneth**
Closes #4

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
mention plox that autocopy requires wl-copy, in both da readme and -h

**Comment by vaxerski** [comment]
I think it's a part of wl-clipboard

**Comment by tmneth** [comment]
mentioned wl-clipboard

**Comment by vaxerski** [comment]
thanks!

**Pull request merged**
